docRoot                         $VH_ROOT
enableGzip                      1

extProcessor panel-backend {
    type                        proxy
    address                     127.0.0.1:8000
    maxConns                    1000
    initTimeout                 60
    retryTimeout                0
    respBuffer                  0
}

context / {
    type                        proxy
    handler                     panel-backend
    addDefaultCharset           off
}

errorlog $SERVER_ROOT/logs/calagopus-panel-error.log {
    useServer                   0
    logLevel                    INFO
    rollingSize                 10M
}

accessLog $SERVER_ROOT/logs/calagopus-panel-access.log {
    useServer                   0
    rollingSize                 10M
    keepDays                    30
    compressArchive             0
    logReferer                  1
    logUserAgent                1
}

accessControl {
    allow                       *
}
