FROM debian:bookworm-slim

RUN apt-get update \
    && apt-get install -y --no-install-recommends ca-certificates libssl3 \
    && rm -rf /var/lib/apt/lists/*

COPY panel-rs /usr/local/bin/panel-rs

ENTRYPOINT ["/usr/local/bin/panel-rs"]
